[book]
authors = ["DaRubyMiner360"]
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/CloudLoaderMC/CloudDocs/tree/main/src"
edit-url-template = "https://github.com/CloudLoaderMC/CloudDocs/edit/main/src/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
